version: "3.4"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dotnetExampleDb
    volumes:
      - ./dotnetexample/Script/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5430:5432

  dotnetexample:
    image: dotnetexample
    container_name: dotnetexample
    environment:
      - "ConnectionStrings:DefaultConnection=Host=postgres;Database=dotnetExampleDb;Username=postgres;Password=root"
    build:
      context: .
      dockerfile: dotnetexample/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - postgres
